#!/bin/bash
#
# jRT
#
jRT_Version=0.0.1

function readlink_f () { _=`pwd`; cd `dirname $1` && echo `pwd` && cd $_; }
INSTALLED_PATH=$(readlink_f $0)

error() {
	echo $*
	exit 1
}

print_help() {
cat <<END
Usage jRT -args=[jRT arguments] <-cmd|java> [ java args ]
END
}

jRT=$INSTALLED_PATH/jRT.jar

if [ -z "$JAVA_HOME" ] ; then
which java 2>&1 > /dev/null && JAVA=java
else
JAVA=$JAVA_HOME/bin/java
fi

[ -z "$JAVA" ] && error "couldn't locate java. Please set JAVA_HOME, or add path to java to PATH variable."

CMD=""

while (( "$#" )); do
	case $1   in
	-args=*)
	jRT_ARGS=$(echo $1 | sed 's/-args=//')
	;;
	-cmd|java)
	[ "$1" == "java" ] && CMD=$JAVA
	shift
	APP=$@
	break
	;;
	-h)
	print_help
	exit 1
	;;
	*)
	print_help
	exit 1
	;;
	esac

	shift
done

export _JAVA_OPTIONS="${_JAVA_OPTIONS} -javaagent:$jRT=$jRT_ARGS"
exec $CMD $APP

